-- Retro Wishlist initial database schema
-- Public clients access wishlist data and reservation mutations only through RPC functions.

create table public.wishlists (
  id bigint generated by default as identity primary key,
  slug text not null,
  title text not null,
  owner_name text not null,
  description text not null default '',
  icon text not null default '🎁',
  visibility text not null default 'public',
  is_featured boolean not null default false,
  is_active boolean not null default true,
  display_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint wishlists_slug_unique unique (slug),
  constraint wishlists_slug_format check (
    slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    and char_length(slug) between 3 and 80
  ),
  constraint wishlists_title_length check (char_length(title) between 1 and 120),
  constraint wishlists_owner_name_length check (
    char_length(owner_name) between 1 and 100
  ),
  constraint wishlists_description_length check (
    char_length(description) <= 1000
  ),
  constraint wishlists_icon_length check (char_length(icon) between 1 and 32),
  constraint wishlists_visibility_valid check (
    visibility in ('public', 'unlisted')
  ),
  constraint wishlists_display_order_valid check (display_order >= 0)
);

create table public.gifts (
  id bigint generated by default as identity primary key,
  wishlist_id bigint not null references public.wishlists(id) on delete cascade,
  gift_key text not null,
  name text not null,
  description text not null default '',
  price text not null default '',
  image text not null default '🎁',
  store_url text,
  accent text not null default 'blue',
  display_order integer not null default 100,
  is_visible boolean not null default true,
  reserved_by text,
  reservation_token uuid,
  reserved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint gifts_wishlist_key_unique unique (wishlist_id, gift_key),
  constraint gifts_key_format check (
    gift_key ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    and char_length(gift_key) between 2 and 100
  ),
  constraint gifts_name_length check (char_length(name) between 1 and 160),
  constraint gifts_description_length check (char_length(description) <= 2000),
  constraint gifts_price_length check (char_length(price) <= 120),
  constraint gifts_image_length check (char_length(image) between 1 and 2048),
  constraint gifts_store_url_length check (
    store_url is null or char_length(store_url) <= 2048
  ),
  constraint gifts_store_url_protocol check (
    store_url is null or store_url ~ '^https://'
  ),
  constraint gifts_accent_valid check (accent in ('blue', 'pink', 'yellow')),
  constraint gifts_display_order_valid check (display_order >= 0),
  constraint gifts_reserved_by_length check (
    reserved_by is null or char_length(reserved_by) between 2 and 50
  ),
  constraint gifts_reservation_state_consistent check (
    (
      reserved_by is null
      and reservation_token is null
      and reserved_at is null
    )
    or
    (
      reserved_by is not null
      and reservation_token is not null
      and reserved_at is not null
    )
  )
);

create index wishlists_directory_idx
  on public.wishlists (display_order, id)
  where is_active = true and visibility = 'public' and is_featured = true;

create index gifts_wishlist_display_idx
  on public.gifts (wishlist_id, display_order, id)
  where is_visible = true;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger wishlists_set_updated_at
before update on public.wishlists
for each row
execute function public.set_updated_at();

create trigger gifts_set_updated_at
before update on public.gifts
for each row
execute function public.set_updated_at();

alter table public.wishlists enable row level security;
alter table public.gifts enable row level security;

revoke all on table public.wishlists from public, anon, authenticated;
revoke all on table public.gifts from public, anon, authenticated;
revoke all on sequence public.wishlists_id_seq from public, anon, authenticated;
revoke all on sequence public.gifts_id_seq from public, anon, authenticated;

create or replace function public.get_featured_wishlists()
returns table (
  slug text,
  title text,
  owner_name text,
  description text,
  icon text,
  total_gifts bigint,
  available_gifts bigint
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    w.slug,
    w.title,
    w.owner_name,
    w.description,
    w.icon,
    count(g.id) as total_gifts,
    count(g.id) filter (where g.reserved_at is null) as available_gifts
  from public.wishlists as w
  left join public.gifts as g
    on g.wishlist_id = w.id
   and g.is_visible = true
  where w.is_active = true
    and w.visibility = 'public'
    and w.is_featured = true
  group by
    w.id,
    w.slug,
    w.title,
    w.owner_name,
    w.description,
    w.icon,
    w.display_order
  order by w.display_order, w.id;
$$;

create or replace function public.get_wishlist(p_wishlist_slug text)
returns table (
  slug text,
  title text,
  owner_name text,
  description text,
  icon text,
  visibility text
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    w.slug,
    w.title,
    w.owner_name,
    w.description,
    w.icon,
    w.visibility
  from public.wishlists as w
  where w.slug = lower(trim(p_wishlist_slug))
    and w.is_active = true
  limit 1;
$$;

create or replace function public.get_wishlist_gifts(p_wishlist_slug text)
returns table (
  id bigint,
  gift_key text,
  name text,
  description text,
  price text,
  image text,
  store_url text,
  accent text,
  display_order integer,
  is_reserved boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    g.id,
    g.gift_key,
    g.name,
    g.description,
    g.price,
    g.image,
    g.store_url,
    g.accent,
    g.display_order,
    g.reserved_at is not null as is_reserved
  from public.gifts as g
  join public.wishlists as w on w.id = g.wishlist_id
  where w.slug = lower(trim(p_wishlist_slug))
    and w.is_active = true
    and g.is_visible = true
  order by g.display_order, g.id;
$$;

create or replace function public.reserve_gift(
  p_wishlist_slug text,
  p_gift_id bigint,
  p_guest_name text,
  p_visitor_token uuid
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_guest_name text := regexp_replace(trim(p_guest_name), '\s+', ' ', 'g');
  v_updated_id bigint;
begin
  if char_length(v_guest_name) not between 2 and 50 then
    raise exception using
      errcode = '22023',
      message = 'Guest name must contain between 2 and 50 characters.';
  end if;

  if p_visitor_token is null then
    raise exception using
      errcode = '22023',
      message = 'Visitor token is required.';
  end if;

  update public.gifts as g
  set
    reserved_by = v_guest_name,
    reservation_token = p_visitor_token,
    reserved_at = now()
  from public.wishlists as w
  where g.id = p_gift_id
    and g.wishlist_id = w.id
    and w.slug = lower(trim(p_wishlist_slug))
    and w.is_active = true
    and g.is_visible = true
    and g.reserved_at is null
  returning g.id into v_updated_id;

  return v_updated_id is not null;
end;
$$;

create or replace function public.release_gift(
  p_wishlist_slug text,
  p_gift_id bigint,
  p_visitor_token uuid
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_updated_id bigint;
begin
  if p_visitor_token is null then
    raise exception using
      errcode = '22023',
      message = 'Visitor token is required.';
  end if;

  update public.gifts as g
  set
    reserved_by = null,
    reservation_token = null,
    reserved_at = null
  from public.wishlists as w
  where g.id = p_gift_id
    and g.wishlist_id = w.id
    and w.slug = lower(trim(p_wishlist_slug))
    and w.is_active = true
    and g.is_visible = true
    and g.reservation_token = p_visitor_token
    and g.reserved_at is not null
  returning g.id into v_updated_id;

  return v_updated_id is not null;
end;
$$;

revoke all on function public.set_updated_at() from public, anon, authenticated;

revoke all on function public.get_featured_wishlists() from public;
revoke all on function public.get_wishlist(text) from public;
revoke all on function public.get_wishlist_gifts(text) from public;
revoke all on function public.reserve_gift(text, bigint, text, uuid) from public;
revoke all on function public.release_gift(text, bigint, uuid) from public;

grant execute on function public.get_featured_wishlists() to anon, authenticated;
grant execute on function public.get_wishlist(text) to anon, authenticated;
grant execute on function public.get_wishlist_gifts(text) to anon, authenticated;
grant execute on function public.reserve_gift(text, bigint, text, uuid)
  to anon, authenticated;
grant execute on function public.release_gift(text, bigint, uuid)
  to anon, authenticated;

comment on table public.wishlists is
  'Wishlist metadata. Public clients must use approved RPC functions.';

comment on table public.gifts is
  'Gift records including private reservation ownership data. Public clients must use approved RPC functions.';

comment on function public.get_featured_wishlists() is
  'Returns active featured public wishlists with safe aggregate gift counts.';

comment on function public.get_wishlist(text) is
  'Returns safe metadata for an active public or exact-slug unlisted wishlist.';

comment on function public.get_wishlist_gifts(text) is
  'Returns visible gifts without guest names, visitor tokens, or reservation timestamps.';

comment on function public.reserve_gift(text, bigint, text, uuid) is
  'Atomically reserves an available visible gift for a browser visitor token.';

comment on function public.release_gift(text, bigint, uuid) is
  'Releases a reservation only when the supplied browser visitor token matches.';
